spring:
  profiles:
    include: >
      game,
      keyboard
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/root
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:/db/changelog-master.xml
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/root
    user: root
    password: root

bot:
  name: QuizzionaireBot
  token: ${BOT_TOKEN:}
