spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/root
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:/db/changelog-master.xml

bot:
  name: TapJustTapBot
  token: ${BOT_TOKEN:}
