game:
  info: |
    🤑 Отвечайте на вопросы и зарабатывайте очки! 
    ❓ Всего 15 вопросов.
    🚒 При правильном ответе на каждый 5-ый вопрос фиксируется несгораемая сумма очков.
    💸 Таблица стоимости каждого вопроса:
    💎 1 - 100
    💎 2 - 200
    💎 3 - 300
    💎 4 - 500
    💎 5 - 1000 - несгораемая сумма 🔥
    💎 6 - 2000
    💎 7 - 4000
    💎 8 - 8000
    💎 9 - 16000
    💎 10 - 32000 - несгораемая сумма 🔥🔥
    💎 11 - 64000
    💎 12 - 125000
    💎 13 - 250000
    💎 14 - 500000
    💎 15 - 1000000 - максимальный выигрыш 🔥🔥🔥
    🚑 У вас есть 3 подсказки:
    5️⃣0️⃣ 50/50 - исключает два неправильных ответа
    👨‍👩‍👧‍👦 Помощь зала - имитация ответа аудитории
    ☎️ Звонок другу - имитация звонка другу
    👋 Удачи!
  score-table:
    1: 100
    2: 200
    3: 300
    4: 500
    5: 1_000
    6: 2_000
    7: 4_000
    8: 8_000
    9: 16_000
    10: 32_000
    11: 64_000
    12: 125_000
    13: 250_000
    14: 500_000
    15: 1_000_000