spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/root
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

bot:
  name: TapJustTapBot
  token: ${BOT_TOKEN:}
