spring:
  profiles:
    include: >
      game,
      keyboard
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/root?currentSchema=quizzionaire_bot}
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:/db/changelog-master.xml
    url: ${DB_URL:jdbc:postgresql://localhost:5432/root?currentSchema=quizzionaire_bot}
    user: root
    password: root

bot:
  name: QuizzionaireBot
  token: ${BOT_TOKEN:}
