CREATE TABLE profile
(
    id                    BIGINT PRIMARY KEY,
    user_name             VARCHAR(255),
    score                 INTEGER,
    correct_answers_count INTEGER,
    passedQuestions       INTEGER
);

CREATE TABLE question
(
    id       INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    question VARCHAR(255),
    answer   VARCHAR(255),
    option1  VARCHAR(255),
    option2  VARCHAR(255),
    option3  VARCHAR(255),
    option4  VARCHAR(255)
);

